

spring:
  config:
    import: s3-local.yml, kinesis-local.yml, dynamo-local.yml, database-local.yml
  jpa:
    hibernate:

      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true

logging:
  level:
    com.mzbr.videoencodingservice: debug
#    com.mzbr.videoencodingservice.service.EncodingServiceImpl: INFO

folder:
  prefix: "encoded-video/"
server:
  port: 0

